export const siteConfig = {
  name: "Clivik Digital Solutions",
  shortName: "Clivik",
  title: "Clivik — WhatsApp Lead Automation for Local Businesses",
  description:
    "Clivik helps local businesses qualify leads, automate WhatsApp follow-ups, run marketing campaigns, gather reviews, and build high-converting websites.",
  url: "https://clivik.netlify.app",
  ogImage: "https://clivik.netlify.app/images/clivik-og.png",
  founder: {
    name: "Arjit Gupta",
    role: "Founder",
    image: "https://res.cloudinary.com/dxvsqh2jw/image/upload/v1790584426/ChatGPT_Image_Sep_28_2026_02_02_51_PM_n7nhui.png",
  },
  contact: {
    phone: "+91 62650 22474",
    phoneClean: "+916265022474",
    email: "helloclivik@gmail.com",
    city: "Bhopal",
    region: "Madhya Pradesh",
    country: "India",
    addressLocality: "Bhopal",
    addressRegion: "Madhya Pradesh",
    postalCode: "462001",
    countryCode: "IN",
    whatsappUrl: "https://wa.me/916265022474",
    whatsappMockupUrl:
      "https://wa.me/916265022474?text=Hi%20Clivik!%20I%27d%20like%20to%20get%20a%20free%20mockup%20for%20my%20business.",
  },
  // Social profile links - centralized for easy future updates
  socials: {
    instagram: process.env.NEXT_PUBLIC_SOCIAL_INSTAGRAM || "",
    facebook: process.env.NEXT_PUBLIC_SOCIAL_FACEBOOK || "",
    linkedin: process.env.NEXT_PUBLIC_SOCIAL_LINKEDIN || "",
    x: process.env.NEXT_PUBLIC_SOCIAL_X || "",
    youtube: process.env.NEXT_PUBLIC_SOCIAL_YOUTUBE || "",
  },
  coreServices: [
    {
      id: "whatsapp-lead-qualification",
      title: "WhatsApp Lead Qualification",
      shortDesc: "Qualify inbound prospects instantly 24/7 without manual back-and-forth.",
      desc: "Instant automated qualification that filters serious buyers from tire-kickers, collects project details, and books appointments straight into your calendar.",
      targetAudience: "Clinics, real estate consultants, gyms, home services, and local agencies.",
      outcome: "Zero missed inquiries, 100% response rate within 5 seconds, and pre-qualified leads ready to close.",
    },
    {
      id: "automated-lead-follow-up",
      title: "Automated Lead Follow-Up",
      shortDesc: "Never let an interested prospect slip through the cracks again.",
      desc: "Timed, multi-step conversational WhatsApp messages that gently follow up with prospects who didn't book or purchase on first contact.",
      targetAudience: "Businesses with long sales cycles or busy owners who forget to follow up.",
      outcome: "Recover 20% to 40% of leads that would otherwise go cold without any manual effort.",
    },
    {
      id: "whatsapp-marketing",
      title: "WhatsApp Marketing",
      shortDesc: "Broadcast high-converting promotions and seasonal offers to your contact list.",
      desc: "Permission-based broadcast campaigns and customer re-engagement workflows that drive repeat visits, repeat orders, and festival sales.",
      targetAudience: "Retail shops, restaurants, salons, clinics, and local ecommerce brands.",
      outcome: "Up to 98% open rates and 45% response rates compared to ignored emails or costly SMS.",
    },
    {
      id: "customer-review-automation",
      title: "Customer Review Automation",
      shortDesc: "Automatically gather 5-star Google reviews from satisfied customers.",
      desc: "Automated post-purchase or post-visit review requests sent over WhatsApp that guide happy clients directly to your Google Business Profile.",
      targetAudience: "Any local business looking to rank higher on Google Maps and win local searches.",
      outcome: "A steady stream of authentic 5-star reviews that boosts Google Maps rankings and local trust.",
    },
    {
      id: "website-development",
      title: "Website Development",
      shortDesc: "Fast, mobile-first websites built to capture leads and drive sales.",
      desc: "Custom-designed, lightning-fast websites integrated with WhatsApp click-to-chat, contact forms, and local SEO to convert visitors into customers.",
      targetAudience: "Local business owners who need a modern online presence delivered in 5 days.",
      outcome: "A professional 24/7 digital storefront that builds authority and drives phone and WhatsApp inquiries.",
    },
  ],
};
